# dev-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-BUILDID
  region: us-east-1

managedNodeGroups:
  - name: ng-BUILDID-workers
    labels: { role: workers }
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 80
    privateNetworking: false
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']